apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo2
spec:
  securityContext:
  containers:
  - name: sec-ctx-demo
    image: registry.k8s.io/e2e-test-images/agnhost:2.45
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 30000
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false