apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: product-service
    environment: staging
    app: app1
  name: product-service
  namespace: space1
spec:
  containers:
  - image: nginx
    name: product-service
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}