apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: rolebinding-role-web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-web
subjects:
- kind: ServiceAccount
  name: service-account-web
  namespace: db